# permissions for end users to edit flavours.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flavour-editor-role
rules:
- apiGroups:
  - nodecore.fluidos.eu
  resources:
  - flavours
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodecore.fluidos.eu
  resources:
  - flavours/status
  verbs:
  - get
