# permissions for end users to view solvers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solver-viewer-role
rules:
  - apiGroups:
      - nodecore.fluidos.eu
    resources:
      - solvers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - nodecore.fluidos.eu
    resources:
      - solvers/status
    verbs:
      - get
